'use strict';
const isFiveM=typeof GetParentResourceName==='function';
const resourceName=isFiveM?GetParentResourceName():'fivemui13';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const ico=id=>'<svg><use href="#'+id+'"></use></svg>';
const money=n=>'$ '+Number(n||0).toLocaleString('de-DE');
const kk=n=>n>=1e6?Math.round(n/1e6)+'kk':money(n);
const cap=s=>String(s||'').charAt(0).toUpperCase()+String(s||'').slice(1);
const price=p=>{p=p||{};let a=[];if(p.cash)a.push('<span class="price cash">'+ico('i-cash')+(p.cash>=1e6?kk(p.cash):money(p.cash))+'</span>');if(p.diamonds)a.push('<span class="price diamond">'+ico('i-diamond')+p.diamonds+'</span>');if(p.lei)a.push('<span class="price lei">'+ico('i-lei')+p.lei+'</span>');return a.length>1?'<div class="multi-price">'+a.join('')+'</div>':(a[0]||'<span class="price cash">FREE</span>')};
const cats=[
['paint','Paint','i-paint','EXTERIOR','Paint & Finish','Normal, matte and metallic use cash. Chrome and chameleon use Diamante.'],
['engine','Engine','i-engine','PERFORMANCE','Engine Stages','Every stage adds 15% maximum speed. Stage 4 Turbo adds a final 30%.'],
['suspension','Suspension','i-suspension','HANDLING','Suspension','Every standard ride-height setup, paid with cash.'],
['armor','Armor','i-armor','PROTECTION','Vehicle Armor','All standard armor levels, paid with cash.'],
['body','Body Parts','i-body','EXTERIOR','Body Components','Only mod slots supported by this vehicle are shown.'],
['livery','Liveries','i-livery','STYLE','Liveries','Vehicle-specific liveries, paid with Diamante.'],
['neon','Neon','i-neon','LIGHTING','Underglow Neon','Custom neon colors and premium rainbow underglow.'],
['headlights','Headlights','i-headlight','LIGHTING','Headlight Color','Custom xenon colors and premium rainbow lights.'],
['smoke','Tire Smoke','i-smoke','EFFECTS','Tire Smoke','Custom smoke colors and premium rainbow smoke.'],
['wheels','Wheels','i-wheel','WHEELS','Wheel Collection','Street, sport, tuner, track, high-end and premium wheels.'],
['sounds','Engine Sounds','i-sound','AUDIO','Engine Sound Library','30 sound profiles from basic street notes to premium popping builds.']
].map(x=>({id:x[0],label:x[1],icon:x[2],eyebrow:x[3],title:x[4],desc:x[5]}));
const swatches=[['Obsidian','#050807'],['Graphite','#252a2d'],['Silver','#9ba3a7'],['Ice White','#edf4f0'],['Crimson','#d91836'],['Inferno','#ff4a21'],['Sunset','#ff8a1d'],['Gold','#d7a629'],['Lime','#5eff42'],['Emerald','#0fc86c'],['Forest','#0a5e38'],['Mint','#59f2b7'],['Cyan','#2dd9ff'],['Electric Blue','#157dff'],['Royal Blue','#2836d8'],['Midnight','#10172f'],['Violet','#7a42ff'],['Purple','#a32cff'],['Hot Pink','#ff3ea7'],['Rose','#d64f71'],['Bronze','#9e633e'],['Sand','#c6ab75'],['Cream','#e4d8b4'],['Smoke','#4a5350']];
const susp=[['s0','Stock Suspension','Factory ride height',0,'STD'],['s1','Street','Subtle daily drop',85000,'S1'],['s2','Sport','Lower center of gravity',165000,'S2'],['s3','Competition','Aggressive track setup',290000,'S3'],['s4','Ultra Low','Maximum supported drop',425000,'LOW']].map(x=>({id:x[0],name:x[1],note:x[2],price:{cash:x[3]},icon:x[4]}));
const armor=[0,20,40,60,80,100].map((v,i)=>({id:'a'+v,name:v?'Armor '+v+'%':'No Armor',note:v?'Reinforcement level '+v+'%':'Factory protection',price:{cash:[0,120000,250000,420000,680000,950000][i]},icon:v+'%',badge:v===100?'MAX':''}));
const stages=[['e0','Factory ECU',0,0,0,0],['e1','Stage 1',1,15,95,0],['e2','Stage 2',2,30,190,0],['e3','Stage 3',3,45,310,0],['e4','Stage 4',4,60,480,0],['et','Stage 4 Turbo',5,90,650,24]].map(x=>({id:x[0],name:x[1],stage:x[2],gain:x[3],price:{diamonds:x[4],lei:x[5]},note:x[2]===5?'Stage 4 plus final +30% boost':'+'+x[3]+'% maximum speed',turbo:x[2]===5}));
const bodyDef='0:spoiler:Spoiler:SPL,1:front-bumper:Front Bumper:FB,2:rear-bumper:Rear Bumper:RB,3:side-skirt:Side Skirts:SK,4:exhaust:Exhaust:EX,5:frame:Frame / Chassis:FR,6:grille:Grille:GR,7:hood:Hood:HD,8:left-fender:Left Fender:LF,9:right-fender:Right Fender:RF,10:roof:Roof:RF,25:plate-holder:Plate Holder:PL,27:trim:Interior Trim:TR,28:ornaments:Ornaments:OR,29:dashboard:Dashboard:DB,30:dials:Dials:DL,31:door-speakers:Door Speakers:DS,32:seats:Seats:ST,33:steering:Steering Wheel:SW,34:shifter:Shifter:SH,35:plaques:Plaques:PQ,36:speakers:Speakers:SP,37:trunk:Trunk:TK,39:engine-block:Engine Block:EB,40:air-filter:Air Filter:AF,41:struts:Struts:SR,42:arch-cover:Arch Covers:AC,43:aerials:Aerials:AR,44:trim2:Secondary Trim:T2,45:tank:Fuel Tank:TK,46:windows:Windows:WN';
const body=bodyDef.split(',').map(s=>{let x=s.split(':');return{modType:+x[0],id:x[1],name:x[2],icon:x[3]}});
const lightColors=[['White','#fff'],['Ice Blue','#bfe9ff'],['Electric Blue','#177dff'],['Cyan','#23e5ff'],['Mint','#6effc4'],['Lime','#72ff2f'],['Green','#13d964'],['Yellow','#ffe033'],['Amber','#ffac22'],['Orange','#ff6a1e'],['Red','#ff293f'],['Pink','#ff48af'],['Purple','#9d45ff'],['Violet','#653cff']];
const soundNames='Compact I4|Street I4|Classic Inline-6|Modern V6|Sport V6|Touring V8|Muscle V8|Race V8|Flat-6 Sport|Twin-Turbo V6|Twin-Turbo V8|Supercharged V8|V10 Road|V10 Race|V12 Grand Tourer|V12 Performance|Boxer Rally|Turbo Rally|Drift I6|Street Racer V6|Street Racer V8|Track V8|Track V10|Hyper V8TT|Hyper V10|Hyper V12|Extreme I6|Extreme V8|Extreme V10|Apex Signature'.split('|');
const soundPrices=[12,18,25,35,45,58,72,88,105,122,140,158,178,198,220,242,265,288,310,330,350,370,392,414,436,455,472,485,495,500];
const sounds=soundNames.map((n,i)=>({id:'snd'+i,name:n,note:i>22?'Premium aggressive profile with pops':i>16?'Aggressive overrun / popping':'Street / performance profile',price:{cash:soundPrices[i]*1e6},icon:String(i+1).padStart(2,'0'),pops:i>16,premium:i>22}));
const liveries=Array.from({length:12},(_,i)=>({id:'liv'+i,name:i?'Livery '+String(i).padStart(2,'0'):'Factory Clean',note:i?'Vehicle-specific graphic package':'No graphics',price:{diamonds:i?55+i*12:0},icon:i?'L'+i:'OEM',value:i-1}));
const wheelGroups=['Street','Sport','Tuner','Track','High End','Muscle','Lowrider','Offroad'], wheels=[];
wheelGroups.forEach((g,t)=>{for(let i=0;i<4;i++){let prem=t>=3&&i>=2;wheels.push({id:'w'+t+'-'+i,name:g+' '+String(i+1).padStart(2,'0'),group:g,wheelType:t,wheelIndex:i,price:prem?{diamonds:120+t*15+i*10}:{cash:225000+t*70000+i*45000},premium:prem})}});
const state={cat:'paint',selected:{},cart:new Map(),finish:'normal',color:'#29e86e',search:'',support:null,vehicle:{name:'OBEY 10F',plate:'RED 013',maxSpeed:205},balances:{cash:12650000,bank:287066000,diamonds:1844,lei:1250}};
const el={app:$('#app'),rail:$('#categoryRail'),content:$('#categoryContent'),scroll:$('#contentScroll'),search:$('#optionSearch'),drawer:$('#cartDrawer'),items:$('#cartItems'),empty:$('#cartEmpty'),count:$('#cartCount'),fab:$('#fabTotal'),cash:$('#totalCash'),dia:$('#totalDiamonds'),lei:$('#totalLei'),checkout:$('#checkoutButton'),confirm:$('#confirmLayer'),ctot:$('#confirmTotals')};
async function post(name,data={}){if(!isFiveM){console.info('[mock]',name,data);return{}}try{return await(await fetch('https://'+resourceName+'/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})).json()}catch(e){console.error(e);return{}}}
function visibleCats(){return cats.filter(c=>c.id!=='livery'||!state.support||Number(state.support['48']||0)>0)}
function rail(){el.rail.innerHTML=visibleCats().map(c=>'<button class="category-button '+(state.cat===c.id?'active':'')+'" data-category="'+c.id+'" data-label="'+c.label+'">'+ico(c.icon)+'</button>').join('');$$('.category-button',el.rail).forEach(b=>b.onclick=()=>setCat(b.dataset.category))}
function setCat(id){state.cat=id;state.search='';el.search.value='';rail();render();el.scroll.scrollTop=0}
function optionList(items,key){let sel=state.selected[key],q=state.search.toLowerCase(),f=items.filter(o=>!q||(o.name+' '+(o.note||'')).toLowerCase().includes(q));if(!f.length)return'<div class="empty-options"><b>No matching options</b>Try another search.</div>';return'<div class="option-list">'+f.map(o=>'<article class="option-card '+(sel&&sel.id===o.id?'selected ':'')+(o.premium?'premium ':'')+'" data-list="'+key+'" data-id="'+o.id+'"><div class="option-icon text-icon">'+(o.icon||'MOD')+'</div><div class="option-copy"><b>'+o.name+(o.badge?' <span class="badge">'+o.badge+'</span>':'')+(o.pops?' <span class="badge">POPS</span>':'')+'</b><small>'+(o.note||'Vehicle upgrade')+'</small></div><div class="option-meta">'+price(o.price)+'</div></article>').join('')+'</div>'}
function simple(items,key,title){let s=state.selected[key]||items[0];return'<div class="section-label"><span>Available setups</span><span>'+items.length+' options</span></div>'+optionList(items,key)+'<div class="add-row"><button class="preview-button" data-preview="'+key+'">Preview</button><button class="add-button" data-add="'+key+'">ADD TO BUILD</button></div>'}
function paintPrice(){return{normal:{cash:50000},matte:{cash:90000},metallic:{cash:125000},chrome:{diamonds:95},chameleon:{diamonds:180}}[state.finish]}
function renderPaint(){let names={normal:'Normal',matte:'Matte',metallic:'Metallic',chrome:'Chrome',chameleon:'Chameleon'};return'<div class="section-label"><span>Finish type</span><span>5 finishes</span></div><div class="finish-tabs">'+Object.keys(names).map(k=>'<button class="finish-tab '+(state.finish===k?'active ':'')+(['chrome','chameleon'].includes(k)?'premium':'')+'" data-finish="'+k+'">'+names[k]+'</button>').join('')+'</div><div class="section-label"><span>Color palette</span><span>'+(['chrome','chameleon'].includes(state.finish)?'DIAMANTE':'CASH')+'</span></div><div class="color-workbench"><input id="nativeColor" type="color" value="'+state.color+'" style="width:100%;height:112px;border:0;background:transparent"><div class="hue-column"><div class="color-readout"><i class="color-chip" style="--selected-color:'+state.color+'"></i><code>'+state.color.toUpperCase()+'</code></div></div></div><div class="swatch-grid">'+swatches.map(x=>'<button class="swatch '+(state.color.toLowerCase()===x[1]?'active':'')+'" style="--swatch:'+x[1]+'" data-color="'+x[1]+'" title="'+x[0]+'"></button>').join('')+'</div><div class="detail-strip"><div class="detail-pill"><small>Finish</small><b>'+names[state.finish]+'</b></div><div class="detail-pill"><small>Color</small><b>'+state.color.toUpperCase()+'</b></div><div class="detail-pill"><small>Price</small><b>'+price(paintPrice())+'</b></div></div><div class="add-row"><button class="preview-button" id="previewPaint">Preview</button><button class="add-button" id="addPaint">ADD TO BUILD</button></div>'}
function renderEngine(){let s=state.selected.engine||stages[0];return'<div class="section-label"><span>ECU calibration</span><span>Every stage +15%</span></div><div class="stage-grid">'+stages.map(o=>'<article class="stage-card '+(o.turbo?'turbo ':'')+(s.id===o.id?'selected':'')+'" data-engine="'+o.id+'"><div class="stage-number">'+(o.turbo?'PREMIUM PERFORMANCE':o.stage?'STAGE 0'+o.stage:'FACTORY')+'</div><h3>'+o.name+(o.turbo?' <span class="badge gold">TURBO</span>':'')+'</h3><p>'+o.note+'</p><div class="stage-price">'+price(o.price)+'</div></article>').join('')+'</div><div class="detail-strip"><div class="detail-pill"><small>Selected</small><b>'+s.name+'</b></div><div class="detail-pill"><small>Gain</small><b>+'+s.gain+'%</b></div><div class="detail-pill"><small>Projected</small><b>'+Math.round(state.vehicle.maxSpeed*(1+s.gain/100))+' KM/H</b></div></div><div class="add-row"><button class="preview-button" data-preview="engine">Preview</button><button class="add-button" data-add="engine">ADD TO BUILD</button></div>'}
function bodyParts(){return state.support?body.filter(p=>Number(state.support[String(p.modType)]||0)>0):body}
function renderBody(){let q=state.search.toLowerCase(),parts=bodyParts().filter(p=>!q||p.name.toLowerCase().includes(q));if(!parts.length)return'<div class="empty-options"><b>No supported body parts</b>This vehicle exposes no matching mod slots.</div>';return'<div class="section-label"><span>Supported components</span><span>'+parts.length+' slots</span></div><div class="option-list">'+parts.map(p=>'<article class="option-card '+(state.selected['body:'+p.modType]?'selected':'')+'" data-part="'+p.modType+'"><div class="option-icon text-icon">'+p.icon+'</div><div class="option-copy"><b>'+p.name+'</b><small>'+(state.support?state.support[String(p.modType)]:'4')+' vehicle-specific variants</small></div><div class="option-meta"><b>OPEN</b><small>configure</small></div></article>').join('')+'</div><div id="bodyConfigurator"></div>'}
function bodyOpts(p){let n=state.support?Number(state.support[String(p.modType)]||0):4,a=[{id:p.id+'-stock',name:'Stock '+p.name,note:'Factory component',price:{cash:0},icon:'OEM',value:-1,modType:p.modType}];for(let i=0;i<n;i++)a.push({id:p.id+'-'+i,name:p.name+' '+String(i+1).padStart(2,'0'),note:'Vehicle-specific variant',price:{cash:85000+i*42000+p.modType*2500},icon:String(i+1).padStart(2,'0'),value:i,modType:p.modType});return a}
function lights(kind){let base=kind==='neon'?42:kind==='headlights'?55:35,rain=kind==='neon'?190:kind==='headlights'?240:165,a=lightColors.map((x,i)=>({id:kind+i,name:x[0],color:x[1],note:cap(kind)+' · '+x[1],price:{diamonds:base+i*2},icon:'CLR'}));a.push({id:kind+'rgb',name:'Rainbow',note:'Premium animated multicolor effect',price:{diamonds:rain},icon:'RGB',premium:true});return a}
function renderLight(kind){let a=lights(kind),s=state.selected[kind];return'<div class="section-label"><span>Color library</span><span>'+a.length+' colors</span></div><div class="swatch-grid">'+a.map(o=>'<button class="swatch '+(o.premium?'rainbow ':'')+(s&&s.id===o.id?'active':'')+'" style="'+(o.color?'--swatch:'+o.color:'')+'" data-light="'+o.id+'" title="'+o.name+'"></button>').join('')+'</div>'+optionList(a,kind)+'<div class="add-row"><button class="preview-button" data-preview="'+kind+'">Preview</button><button class="add-button" data-add="'+kind+'">ADD TO BUILD</button></div>'}
function renderWheels(){let s=state.selected.wheels,q=state.search.toLowerCase(),a=wheels.filter(o=>!q||(o.name+' '+o.group).toLowerCase().includes(q));return'<div class="section-label"><span>Wheel designs</span><span>'+a.length+' results</span></div><div class="wheel-grid">'+a.map(o=>'<article class="wheel-card '+(s&&s.id===o.id?'selected':'')+'" data-wheel="'+o.id+'"><div class="wheel-art">'+ico('i-wheel')+'</div><span class="badge '+(o.premium?'diamond':'')+'">'+(o.premium?'PREMIUM':o.group)+'</span><h3>'+o.name+'</h3><small>'+(o.premium?'Diamante collection':'Cash collection')+'</small><div class="wheel-price">'+price(o.price)+'</div></article>').join('')+'</div><div class="add-row"><button class="preview-button" data-preview="wheels">Preview</button><button class="add-button" data-add="wheels">ADD TO BUILD</button></div>'}
function renderSounds(){let s=state.selected.sounds,q=state.search.toLowerCase(),a=sounds.filter(o=>!q||(o.name+' '+o.note).toLowerCase().includes(q));return'<div class="section-label"><span>Sound profiles</span><span>12kk — 500kk</span></div><div class="option-list">'+a.map(o=>'<article class="option-card sound-row '+(s&&s.id===o.id?'selected ':'')+(o.premium?'premium':'')+'" data-sound="'+o.id+'"><div class="option-icon text-icon">'+o.icon+'</div><div class="option-copy"><b>'+o.name+(o.pops?' <span class="badge">POPS</span>':'')+(o.premium?' <span class="badge diamond">PREMIUM</span>':'')+'</b><small>'+o.note+'</small></div><button class="play-button" data-play="'+o.id+'">'+ico('i-sound')+'</button><div class="option-meta">'+price(o.price)+'</div></article>').join('')+'</div><div class="add-row"><button class="preview-button" data-preview="sounds">Preview</button><button class="add-button" data-add="sounds">ADD TO BUILD</button></div>'}
function render(){let c=cats.find(x=>x.id===state.cat)||cats[0];$('#panelEyebrow').textContent=c.eyebrow;$('#panelTitle').textContent=c.title;$('#panelDescription').textContent=c.desc;if(c.id==='paint')el.content.innerHTML=renderPaint();else if(c.id==='engine')el.content.innerHTML=renderEngine();else if(c.id==='suspension')el.content.innerHTML=simple(susp,'suspension','Suspension');else if(c.id==='armor')el.content.innerHTML=simple(armor,'armor','Armor');else if(c.id==='body')el.content.innerHTML=renderBody();else if(c.id==='livery')el.content.innerHTML=simple(liveries,'livery','Livery');else if(['neon','headlights','smoke'].includes(c.id))el.content.innerHTML=renderLight(c.id);else if(c.id==='wheels')el.content.innerHTML=renderWheels();else el.content.innerHTML=renderSounds();bind();hud()}
function preview(key,o){if(!o)return;post('preview',{category:state.cat,key,id:o.id,value:o.value??o.stage??o.wheelIndex??null,meta:o});toast('Previewing <b>'+o.name+'</b>')}
function add(key,o,title){if(!o)return;state.cart.set(key,{key,category:title,id:o.id,name:o.name,price:{...(o.price||{})},meta:{...o}});cart();toast('Added <b>'+o.name+'</b> to your build')}
function choose(key,o){if(!o)return;state.selected[key]={...o};render();preview(key,o)}
function bind(){
$$('[data-list]',el.content).forEach(n=>n.onclick=()=>{let k=n.dataset.list,a=k==='suspension'?susp:k==='armor'?armor:k==='livery'?liveries:lights(k);choose(k,a.find(x=>x.id===n.dataset.id))});
$$('[data-engine]',el.content).forEach(n=>n.onclick=()=>choose('engine',stages.find(x=>x.id===n.dataset.engine)));
$$('[data-wheel]',el.content).forEach(n=>n.onclick=()=>choose('wheels',wheels.find(x=>x.id===n.dataset.wheel)));
$$('[data-sound]',el.content).forEach(n=>n.onclick=e=>{if(!e.target.closest('[data-play]'))choose('sounds',sounds.find(x=>x.id===n.dataset.sound))});
$$('[data-play]',el.content).forEach(n=>n.onclick=e=>{e.stopPropagation();preview('sounds',sounds.find(x=>x.id===n.dataset.play))});
$$('[data-light]',el.content).forEach(n=>n.onclick=()=>choose(state.cat,lights(state.cat).find(x=>x.id===n.dataset.light)));
$$('[data-preview]',el.content).forEach(n=>n.onclick=()=>{let k=n.dataset.preview,o=state.selected[k]||(k==='engine'?stages[0]:k==='suspension'?susp[0]:k==='armor'?armor[0]:k==='livery'?liveries[0]:null);preview(k,o)});
$$('[data-add]',el.content).forEach(n=>n.onclick=()=>{let k=n.dataset.add,o=state.selected[k]||(k==='engine'?stages[0]:k==='suspension'?susp[0]:k==='armor'?armor[0]:k==='livery'?liveries[0]:null);add(k,o,cap(k))});
$$('[data-part]',el.content).forEach(n=>n.onclick=()=>openPart(+n.dataset.part));
if(state.cat==='paint'){ $$('.finish-tab',el.content).forEach(n=>n.onclick=()=>{state.finish=n.dataset.finish;render();paintPreview()}); $$('.swatch',el.content).forEach(n=>n.onclick=()=>{state.color=n.dataset.color;state.selected.paint={id:'p-'+state.finish+'-'+state.color,name:cap(state.finish)+' · '+state.color.toUpperCase(),price:paintPrice(),color:state.color,finish:state.finish};render();paintPreview()}); let col=$('#nativeColor',el.content);if(col)col.oninput=e=>{state.color=e.target.value;state.selected.paint={id:'p-'+state.finish+'-'+state.color,name:cap(state.finish)+' · '+state.color.toUpperCase(),price:paintPrice(),color:state.color,finish:state.finish};paintPreview(false)};$('#previewPaint',el.content).onclick=()=>paintPreview();$('#addPaint',el.content).onclick=()=>{let o=state.selected.paint||{id:'p-'+state.finish+'-'+state.color,name:cap(state.finish)+' · '+state.color.toUpperCase(),price:paintPrice(),color:state.color,finish:state.finish};state.selected.paint=o;add('paint',o,'Paint')}}
}
function paintPreview(show=true){let o=state.selected.paint||{id:'p-'+state.finish+'-'+state.color,name:cap(state.finish)+' · '+state.color.toUpperCase(),price:paintPrice(),color:state.color,finish:state.finish};post('preview',{category:'paint',key:'paint',id:o.id,value:state.color,meta:o});if(show)toast('Previewing <b>'+o.name+'</b>')}
function openPart(type){let p=body.find(x=>x.modType===type),a=bodyOpts(p),key='body:'+type,host=$('#bodyConfigurator',el.content);host.innerHTML='<div class="section-label" style="margin-top:16px"><span>'+p.name+'</span><span>'+a.length+' choices</span></div>'+optionList(a,key)+'<div class="add-row"><button class="preview-button" id="pBody">Preview</button><button class="add-button" id="aBody">ADD COMPONENT</button></div>';$$('[data-list="'+key+'"]',host).forEach(n=>n.onclick=()=>{state.selected[key]=a.find(x=>x.id===n.dataset.id);openPart(type);preview(key,state.selected[key])});$('#pBody',host).onclick=()=>preview(key,state.selected[key]||a[0]);$('#aBody',host).onclick=()=>add(key,state.selected[key]||a[0],p.name);host.scrollIntoView({behavior:'smooth',block:'nearest'})}
function totals(){let t={cash:0,diamonds:0,lei:0};state.cart.forEach(x=>{t.cash+=x.price.cash||0;t.diamonds+=x.price.diamonds||0;t.lei+=x.price.lei||0});return t}
function plain(p){let a=[];if(p.cash)a.push(p.cash>=1e6?kk(p.cash):money(p.cash));if(p.diamonds)a.push(p.diamonds+' ◆');if(p.lei)a.push(p.lei+' L');return a.join(' + ')||'FREE'}
function cart(){let a=[...state.cart.values()],t=totals();el.count.textContent=a.length;el.empty.classList.toggle('hidden',a.length>0);el.items.innerHTML=a.map(x=>'<div class="cart-item"><div><b>'+x.name+'</b><small>'+x.category+'</small></div><span class="cart-item-price">'+plain(x.price)+'</span><button class="remove-item" data-remove="'+x.key+'">'+ico('i-close')+'</button></div>').join('');el.cash.textContent=money(t.cash);el.dia.textContent=t.diamonds+' ◆';el.lei.textContent=t.lei+' L';el.checkout.disabled=!a.length;el.fab.textContent=a.length?plain(t):'No parts selected';$$('[data-remove]',el.items).forEach(n=>n.onclick=()=>{state.cart.delete(n.dataset.remove);cart()});hud()}
function hud(){let e=state.cart.get('engine')?.meta||state.selected.engine||stages[0],g=e.gain||0;$('#stockSpeed').textContent=Math.round(state.vehicle.maxSpeed);$('#projectedSpeed').textContent=Math.round(state.vehicle.maxSpeed*(1+g/100));$('#speedGain').textContent='+'+g+'%';$('#powerMeter').style.width=Math.min(100,g/90*100)+'%'}
function wallet(){$('#cashBalance').textContent=money(state.balances.cash);$('#bankBalance').textContent=money(state.balances.bank);$('#diamondBalance').textContent=Number(state.balances.diamonds).toLocaleString('de-DE');$('#leiBalance').textContent=Number(state.balances.lei).toLocaleString('de-DE')}
function vehicle(){$('#vehicleName').textContent=state.vehicle.name;$('#vehicleHudName').textContent=state.vehicle.name;$('#vehiclePlate').textContent=state.vehicle.plate;hud()}
function toast(h){let n=document.createElement('div');n.className='toast';n.innerHTML=h;$('#toastStack').appendChild(n);setTimeout(()=>{n.style.opacity='0';setTimeout(()=>n.remove(),250)},2100)}
async function support(){let r=await post('requestVehicleSupport',{});if(r&&r.supported){state.support=r.supported;if(state.cat==='livery'&&!Number(r.supported['48']||0))state.cat='paint';rail();render()}}
function closeUI(){el.drawer.classList.remove('open');el.confirm.classList.remove('show');el.app.classList.remove('is-visible');post('close',{})}
$('#buildFab').onclick=()=>el.drawer.classList.add('open');$('#closeCart').onclick=()=>el.drawer.classList.remove('open');$('#closeUi').onclick=closeUI;$('#clearBuild').onclick=()=>{state.cart.clear();cart();post('revertPreview',{all:true});toast('Build cleared')};
el.checkout.onclick=()=>{let t=totals();el.ctot.innerHTML=(t.cash?'<span class="confirm-total">'+money(t.cash)+' cash</span>':'')+(t.diamonds?'<span class="confirm-total">'+t.diamonds+' ◆ Diamante</span>':'')+(t.lei?'<span class="confirm-total">'+t.lei+' Lei</span>':'');el.confirm.classList.add('show')};
$('#cancelCheckout').onclick=()=>el.confirm.classList.remove('show');$('#confirmCheckout').onclick=async()=>{await post('checkout',{items:[...state.cart.values()],totals:totals(),vehicle:state.vehicle});el.confirm.classList.remove('show');el.drawer.classList.remove('open');state.cart.clear();cart();toast('<b>Build submitted.</b> Server validation pending.')};
$('#resetCategory').onclick=()=>{Object.keys(state.selected).filter(k=>k===state.cat||k.startsWith(state.cat+':')||(state.cat==='body'&&k.startsWith('body:'))).forEach(k=>delete state.selected[k]);if(state.cat==='paint'){state.finish='normal';state.color='#29e86e'}render();post('revertPreview',{category:state.cat})};
el.search.oninput=e=>{state.search=e.target.value.trim();render()};
document.onkeydown=e=>{if(e.key!=='Escape')return;if(el.confirm.classList.contains('show'))return el.confirm.classList.remove('show');if(el.drawer.classList.contains('open'))return el.drawer.classList.remove('open');closeUI()};
window.addEventListener('message',e=>{let d=e.data||{};if(d.action==='open'){if(d.vehicle)state.vehicle={...state.vehicle,...d.vehicle};if(d.balances)state.balances={...state.balances,...d.balances};wallet();vehicle();el.app.classList.add('is-visible');support()}if(d.action==='close')el.app.classList.remove('is-visible');if(d.action==='setBalances'&&d.balances){state.balances={...state.balances,...d.balances};wallet()}if(d.action==='setVehicle'&&d.vehicle){state.vehicle={...state.vehicle,...d.vehicle};vehicle()}if(d.action==='setSupportedMods'&&d.supported){state.support=d.supported;rail();render()}if(d.action==='checkoutResult')toast(d.ok?'<b>Installed successfully.</b> Enjoy the build.':'<b>Purchase failed.</b> '+(d.message||'Check your balance.'))});
if(isFiveM)el.app.classList.remove('is-visible');wallet();vehicle();rail();render();cart();
